/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javadolghelp;

/**
 *
 * @author Diak
 */
public class UjPanel extends javax.swing.JPanel {

    /**
     * Creates new form UjPanel
     */
    public UjPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Születési hely:");
        add(jLabel1);
        jLabel1.setBounds(10, 90, 90, 16);

        jLabel2.setText("Születési dátum:");
        add(jLabel2);
        jLabel2.setBounds(10, 60, 100, 16);

        jLabel3.setText("Anyja neve:");
        add(jLabel3);
        jLabel3.setBounds(10, 120, 70, 16);

        jLabel4.setText("Név:");
        add(jLabel4);
        jLabel4.setBounds(10, 30, 37, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
